### PR TITLE
Preventing xss in job calendar

### PR DESCRIPTION
**Pull request by dvenor**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by dvenor** [comment]
**lurch: attach W-024326

**Comment by dvenor** [comment]
You may run into an error deploying V4S into scratch orgs using the `dev_org` flow.  RelEng is currently investigating and has provided this workaround:

`cci task run deploy -o clean_meta_xml False
cci flow run dev_org --skip deploy`

**Comment by dvenor** [comment]
**lurch: attach W-026320

**Comment by dvenor** [comment]
**lurch: detach W-026320

**Comment by dvenor** [comment]
**lurch: attach W-026320

**Comment by jjbennett** [comment]
@dvenor - tested the new url and works great, it's great it got done in time, one PR one release :)

**Comment by rponti-sforg** [comment]
QE testing for this PR is complete.  Tests have passed.

For testing details, see:
https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x8000000AVyplAAD/view
https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x8000000AYBwMAAX/view

Merging PR and deleting branch.

**Pull request merged**
