### PR TITLE
Fix for issue #295 - custom fields with "other" or "mailing" not saving

### PR DESCRIPTION
**Pull request by astudd**
Hi,

This is my first pull request - I hope I did it correctly (apologies if I didn't).

Replicating the logic implemented for Other and Mailing addresses in the existing contact scenario for new Contacts. Copied the logic from lines 530 and 534 to lines 567 and 571

### CODE REVIEW

**Comment by astudd** [comment]
I just realized that this will still not handle the issue for the "Other Phone" field, since that is a standard field.  I wanted to minimize my changes, but it might be a good idea to add logic to exclude "otherphone" explicitly as well to both the existing and new scenarios.

**Comment by davidhabib** [comment]
@judisohn

**Comment by judisohn** [comment]
Hi @astudd - thank you so much for the contribution. I will add this to our backlog and a developer should be able to review and consider it hopefully over the next few sprints. In the meantime, could you email me at jsohn@salesforce.com so I have your contact information directly? Thank you!

**Comment by davidhabib** [comment]
Thanks @astudd for this contribution.  I'm closing this pull request as I've incorporated this into the following pull request that will then run through our build system.  thanks again!
https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/pull/333

**Pull request closed without merging**
