### PR TITLE
Add hours cross filter to Volunteer Roster

### LINKED ISSUE #280: Filter on Volunteer Roster does not work due to custom report type
[Thread 1](https://powerofus.force.com/0D58000003KE3ka) and [2](https://powerofus.force.com/0D58000003HU1bU) (same customer).

Replicated in test org. I believe the challenge is that we changed the custom report type to a WITH or WITHOUT join, and the filter is on the child object. See this [Help & Training document](https://help.salesforce.com/articleView?id=000004402&language=en_US&type=1), and [related blog post](http://www.simplysfdc.com/2015/02/salesforce-report-with-filter-on-child.html). Need to rethink how this report is generated... perhaps with cross filter as recommended?

### PR DESCRIPTION
**Pull request by jjbennett**
# Critical Changes

# Changes

# Issues Closed
- Fixes #280 

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by jjbennett** [comment]
**lurch: attach W-018262

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005kjeNAAQ" target="_blank">W-018262</a>

**Comment by jjbennett** [comment]
@coriobriensfdo - It looks like just adding the hours cross filter should do the trick. Can you please take a look at this branch to confirm?

**Comment by lmeerkatz** [comment]
@jjbennett I believe you said existing customers would need to make these changes manually. If so, can you take a first pass at writing up steps to do so?

**Comment by coriobriensfdo** [comment]
@jjbennett I tested in a scratch org with your new feature branch and the roster report is working as expected in both Classic and Lightning, via the Campaign, Job, and Shift. Thanks!

**Comment by jjbennett** [comment]
Determined a different path forward.

**Pull request closed without merging**
