### PR TITLE
Origin/Destinations/Maps/Driving Directions on Shifts

### LINKED ISSUE #170: Destination and Driving Directions in Job and Shift and JobListingFS display
I've currently got a use case (and have seen this need before) for not just showing a location for a Job, but showing an origin and a destination with driving directions. (Volunteers providing transportation to seniors for their doctors' appointments, for instance.)

I'd also like to see this available at the *Shift* level, not just the Job level, on JobListingFS.

I'm working on both of these.

### PR DESCRIPTION
**Pull request by bethbrains**
Closes #170. 
Added Location/Origin and Destination Address blocks on Volunteer Shift object, along with a picklist to select how the Shift map should appear on VolunteerJobListingFS. Used a picklist so admins can set preferred behaviour as default value.

### CODE REVIEW

**Comment by davidhabib** [comment]
Beth, thanks for the contribution, but I must admit the use case of having different locations for Shifts seems very rare to me, so I am a bit uncomfortable adding all these address fields to Shifts.  What is your use case that made you come up with this solution?  Why was it not better served by locations on Job?  Can you also point me at the Sites page so I can see what this looks like to the user.  thanks.

**Comment by bethbbc** [comment]
Valid questions! Sorry for not providing more details on the use case.

We've seen this with a few orgs now that provide transportation services, like volunteers to non-driving elders for transportation to appointments/shopping/etc. The "Job" is something like "Medical Transportation", and each shift (day/time) is for a different Client/Care Receiver/Senior (custom lookup to Contact), going from their home (origin address) to a doctor's appointment (destination address). To do this on Job (even with adding destination and directions), it would require a Job for each individual Shift to be able to offer online volunteer sign-up. 

Other "Jobs" might include "Visiting", which would likewise have separate Shifts for each client, each with its own address, though in this case just a location, no destination and no directions.

http://bbcontrib-developer-edition.na22.force.com/VolunteersJobListingFS Shows both scenarios. 

Let me know what you think! Happy to discuss further!

**Comment by davidhabib** [comment]
Hi Beth, I'm going to sit on this until I have a chance next week to discuss with others and maybe get feedback on the Hub about this feature.  Thanks.  Have a Happy New Year!

**Comment by bethbbc** [comment]
Sounds good! You too!

**Comment by davidhabib** [comment]
@mpusto Please review and give feedback.  I'm uncomfortable adding all these address fields to Shifts. Job already contains address fields and the Sites pages are optimized to display address info only for the Job.  I believe it will confuse many users, and only will help a very small set of users.  I'd suggest those users who need it can add it themselves as Beth has done for her client.

**Comment by davidhabib** [comment]
@mpusto can we close this, or are you still considering?

**Comment by mpusto** [comment]
I think I'd like to see more requests prior to deciding on this, so if we had an Idea and votes it might help me get a better sense of the demand. I've been talking to various folks about volunteer features and this has yet to come up

**Pull request closed without merging**
