### PR TITLE
Add Telemetry for grant users update access boolean value

### PR DESCRIPTION
**Pull request by jjbennett**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by jjbennett** [comment]
@katherinemitchell - adding you to this pull request since the telemetry doc will need to include this new boolean feature parameter. We have only had integer values before so let me know if you need a new screen shot or perhaps we can snag one from NPSP?

**Comment by jjbennett** [comment]
**lurch: attach W-035262

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C9KxQAK" target="_blank">W-035262</a>

**Comment by scottwarren-sfdo** [comment]
Failing tests are being addressed in a subsequent PR.

**Pull request merged**
