### PR TITLE
SLDS'ing of Mass Enter Volunteer Hours, and shared util components

### PR DESCRIPTION
**Pull request by davidhabib**
# Critical Changes

# Changes
- The Mass Enter Volunteer Hours page has now been updated to use Lightning styling to provide consistency with Lightning Experience.

# Issues Closed

### CODE REVIEW

**Comment by davidhabib** [comment]
@jjbennett @njjc This is not ready for merge.  I still need to investigate a few issues that only happen under LEX, as well as I'd like to include the work to have this page correctly do the related list refresh of hours, just like Jenn added to NPSP.  Not sure I'll finish that work before I leave town.

**Comment by davidhabib** [comment]
I should have added, however, that if it will make life easier for you two to merge this now, so you get the UTIL page messages component, that's ok.  I won't close my AA item until I feel I've resolved the other issues I just mentioned.  thanks.

**Comment by davidhabib** [comment]
@jjbennett @njjc OK, ready for review and merge.  This pull request now includes Jenni's UTIL_NavigateBack component, which will correctly refresh the calling page in LEX.

**Comment by njjc** [comment]
Couple of doorknobs to polish in the Bulk Enter Hours UI: 

When the picklists have no options for selection, there is still the default blank picklist option, and selecting it feels weird:
screen shot 2016-11-04 at 2 48 53 pm

All the picklists in the page should be disabled if their number of picklist options is 1, as they all have the blank first option. Disabled, they look like this:
screen shot 2016-11-04 at 2 46 06 pm

My other issue is with the campaign/job/shift selection in the images above; the flow of attention and the tab order of the fields is left to right, then top to bottom; it feels a bit disjointed going "Campaign -> Show Shifts & Hours From (Date) -> Volunteer Job -> To (Date) -> Volunteer Shift".

I think the field order should be Campaign -> Job -> Shift, and both date fields on the next line.

@davidhabib @jjbennett

**Comment by njjc** [comment]
@davidhabib I'm merging this in so we can use the shared component, but we should address the issues above when you're back.

**Comment by davidhabib** [comment]
@mpusto These are changes from the current implementation and should be treated as a new work item if you think they should be done.  I agree the layout change might be an improvement.  As for disabling the dependent picklists, I'm not sure what the LEX standard is for this, and we should not do anything different than what LEX does, so we need direction if you are asking for a change.  thanks.

**Comment by njjc** [comment]
So I shouldn't have merged it? :) These are pretty clear UX issues.

**Comment by davidhabib** [comment]
no I'm glad you merged it.  I'm just asking Mary to enter a new work item for the enhancements you called out, since this one is closed and there is no AA item.  And I'm also asking her to clarify how dependent picklists should get handled under LEX.

**Comment by mpusto** [comment]
I've asked for clarification from Jade and I'll add a work item as well.

**Pull request merged**
