### PR TITLE
Find Volunteers SLDS

### PR DESCRIPTION
**Pull request by njjc**
# Critical Changes

# Changes
- Find Volunteers page has been updated to use Salesforce Lightning Design System.

# Issues Closed

### CODE REVIEW

**Comment by davidhabib** [comment]
@njjc the build is failing because you are referring to a resource that Jenny changed.

**Comment by davidhabib** [comment]
@njjc looks like you stuck with the vertical design for the criteria section.  Unfortunately, I feel like this makes the page rather unpleasant on a non-mobile display, which is the vast use case.  Would you like me to take a crack at getting the criteria section horizontally laid out?

**Comment by njjc** [comment]
@davidhabib I've found a hack to fix it by getting the size of the field set and using it with an slds-grid. It might bork with over 12 fields in the set, and it might be squeezed as the number of elements gets bigger, but I think the old page was the same way.

**Comment by davidhabib** [comment]
@njjc please look at this last minor commit I added to make sure you are OK with it.  Hope to get in one more to improve placement of selection checkboxes in the Contact section.

**Comment by njjc** [comment]
Works for me!

**Comment by davidhabib** [comment]
ok, @njjc, one more minor tweak. if it looks good to you, i'll merge this pull request.  thanks!

**Comment by njjc** [comment]
Looks good @davidhabib. Do you think we should add help text to explain ctrl/cmd+click to select multiple options?

**Comment by davidhabib** [comment]
@njjc I believe LEX is adding support for popup help of field descriptions in 206 or 208.  we should wait until then, and then we can leverage what they provide.  But now I'm wondering whether your work still left the criteria help "Choose your criteria and click Find. Volunteers match if any of the selected values within a field match. Leave a criteria blank, to not filter on it.".  I just deployed Jenni's branch to my org, so now I can't see your work!

**Comment by njjc** [comment]
Yeah, it has that label. I was just thinking of adding a little extra text
to that label to clarify. Do you think the change you're talking about will
affect custom visualforce? I doubt it.

**Comment by davidhabib** [comment]
I'd expect it to add the help bubbles where we use inputField.

**Pull request merged**
