### PR TITLE
Feature/jen hebrew

### PR DESCRIPTION
**Pull request by jjbennett**
Adding Hebrew to the Package
# Critical Changes

# Changes
- The V4S package now includes Hebrew translations.

# Issues Closed

### CODE REVIEW

**Comment by davidhabib** [comment]
@jjbennett @mpusto do either of you recall where we stand with this hebrew translation pull request for V4S.  I vaguely remember testing it out several months ago, but can't remember if I identified issues that needed to be dealt with, or if there was a reason I did not merge it in.

**Comment by mpusto** [comment]
I think we were waiting to merge when we had other things to release

On Sep 23, 2017, at 12:36 PM, David Habib <notifications@github.com> wrote:

@jjbennett <https://github.com/jjbennett> @mpusto
<https://github.com/mpusto> do either of you recall where we stand with
this hebrew translation pull request for V4S. I vaguely remember testing it
out several months ago, but can't remember if I identified issues that
needed to be dealt with, or if there was a reason I did not merge it in.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/pull/289#issuecomment-331656289>,
or mute the thread

**Comment by jjbennett** [comment]
@davidhabib it might have been because the builds were failing and when they passed we merged Cumulus but not V4S?

**Comment by davidhabib** [comment]
OK, I did some digging and found this quip doc that shows the issues I ran into. 
https://salesforce.quip.com/FtiqAwMvOzTV
Some were translation issues that the translators must fix.  others were display issues that require real work on our side to correctly deal with a right to left language. 
@mpusto do you want us to release what we have, wait for the translation fixes, or wait for all the right-to-left fixes (which we still need work items for)?  thanks.

**Comment by davidhabib** [comment]
@mpusto it's worth noting that some of the display problems i found with hebrew also occur with NPSP (not surprisingly).  I also see that we've added several new objects like Levels and Engagement Plans that aren't translated in Hebrew in NPSP.  So I'm not sure if that changes what the bar should be for V4S.

**Comment by jjbennett** [comment]
@davidhabib this should be ready to go now once Hebrew has been enabled in the packaging org.

**Pull request merged**
