### PR TITLE
Allow for business account for volunteers

### PR DESCRIPTION
**Pull request by dschach**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by dschach** [comment]
@judisohn Form signed. Any updates on this pull request?

**Comment by coriobriensfdo** [comment]
**Lurch: add

**Comment by coriobriensfdo** [comment]
Thanks for sending over the form @dschach! We'll get it reviewed by the Volunteers team and go from there. Someone will be in touch, but it note that due to existing scheduled projects it may be a little while before this can be reviewed.

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAMxQAO" target="_blank">W-035831</a>

**Comment by dschach** [comment]
Thank you @coriobriensfdo - I wasn't able to submit as a separate pull request, but the Visualforce page update is a very simple one to display the org name and current year, not the hard-coded 2016, in the template footer.

**Pull request closed without merging**
