### PR TITLE
Disable Mass Hour Update Buttons During Save

### PR DESCRIPTION
**Pull request by scottwarren-sfdo**
# Critical Changes

# Changes

# Issues Closed
- Fixes: [#271](https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/issues/271#issuecomment-287424957)

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by scottwarren-sfdo** [comment]
**lurch: attach W-018124

**Comment by lmeerkatz** [comment]
**lurch:attach W-018124

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000005QCqVAAW" target="_blank">W-018124</a>

**Comment by aumouth** [comment]
Still an open bug with very recent impact.
https://github.com/SalesforceFoundation/Volunteers-for-Salesforce/issues/527
https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000Bu1msSAB

**Pull request merged**
